language: java

jdk:
  - openjdk8

matrix:
  fast_finish: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.ivy2/cache
    - $HOME/.m2/repository
    - $HOME/.sbt

script:
  - (cd openapi/java && ./mvnw clean verify)
  - (cd openapi/scala && ./sbt clean test)
  - (cd jpa-crud/java-sbt && ./sbt clean test)

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/9e04688b0ae124f5a047"
      - "https://webhooks.gitter.im/e/869b1a645dc46645e619"
    on_success: change
    on_failure: always
    on_start: never